on:
  workflow_call:
    inputs:
      REGISTRY: { required: false, type: string, default: ghcr.io }
      IMAGE_NAME: { required: true, type: string }

env:
  IMAGE_REG: "${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: docker/setup-qemu-action@v3.7.0
      - uses: docker/setup-buildx-action@v3.12.0

      - uses: docker/login-action@v3.6.0
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5.10.0
        with:
          images: "${{ env.IMAGE_REG }}"
          tags: |
            type=raw,value=latest
            type=sha
        id: meta

      - uses: docker/build-push-action@v6.18.0
        with:
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-to: type=gha,mode=max
          cache-from: type=gha
          context: .
