on:
  workflow_call:
    inputs:
      REGISTRY: { required: false, type: string, default: ghcr.io }
      IMAGE_NAME: { required: true, type: string }

env:
  IMAGE_REG: "${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-24.04${{ matrix.platform == 'linux/arm64' && '-arm' || '' }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6.0.0
      - uses: docker/login-action@v3.6.0
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          PLATFORM=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${PLATFORM//\//-}" >> $GITHUB_ENV

      - uses: docker/metadata-action@v5.9.0
        with: { images: "${{ env.IMAGE_REG }}" }
        id: meta

      - run: docker context create builders
        id: buildx-context

      - uses: docker/setup-buildx-action@v3.11.1
        with: { endpoint: builders, platforms: "${{ matrix.platform }}" }

      - uses: docker/build-push-action@v6.18.0
        with:
          context: .
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: type=image,name=${{ env.IMAGE_REG }},push-by-digest=true,name-canonical=true,oci-mediatypes=true
          cache-from: type=gha,scope=${{ github.repository }}-${{ github.ref_name }}-${{ matrix.platform }}
          cache-to: type=gha,scope=${{ github.repository }}-${{ github.ref_name }}-${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
        id: build

      - name: Export digest
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v6.0.0
        if: github.event_name != 'pull_request'
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          if-no-files-found: error
          path: /tmp/digests/*
          retention-days: 1
  # =============================================================================

  publish:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/download-artifact@v7.0.0
        with: { path: /tmp/digests, pattern: digests-*, merge-multiple: true }
      - uses: docker/setup-buildx-action@v3.11.1

      - uses: docker/login-action@v3.6.0
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5.9.0
        id: meta
        with:
          images: ${{ env.IMAGE_REG }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.IMAGE_REG }}@sha256:%s ' *)
  # =============================================================================
